### ISSUE TITLE
Error: The requested blob is too large to fetch via the API

### ISSUE THREAD

**Issue by LucianoBestia** [serayuzgur/crates#71] opened 2020-01-11 07:00 UTC
I use Crates 0.4.7. VSCode Extension on windows with Remote -WSL. The code is actually inside Windows Subsystem for Linux (Debian 10 backend) and only the frontend is in windows. 
In my cargo.toml the  Crates Extension  draws a red exclamation sign near web.sys like this:

[dependencies.web-sys]
version = "0.3.27"   **!**
features = [
  "AbortController",
  "console",
....

The error msg is:
web-sys: StatusCodeError: 403 -
 "{"message":"This API returns blobs up to 1 MB in size. 
 The requested blob is too large to fetch via the API, 
 but you can use the Git Data API to request blobs up to 100 MB in size.",
 "errors":[{"resource":"Blob","field":"data","code":"too_large"}],
 "documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents\"}"

Is it possible to correct this error?

Thanks

**Comment by serayuzgur** [comment] 2020-01-11 20:19
wow it is , but it may take some time. Also I am planning to code my own index server for version fetching but not enough sponsors right now so I have to check Data API first.

**Comment by LucianoBestia** [comment] 2020-01-15 06:56
Do you use this api ?
https://crates.io/api/v1/crates/web-sys

**Comment by serayuzgur** [comment] 2020-01-16 10:24
I was using it before then crates.io stated that i should use (github) index or extension will be banned because of call rates.

**Comment by serayuzgur** [comment] 2020-01-28 06:49
I am referencing @LucianoBestia  's code to make it visible more [cargo_reg_local](https://github.com/LucianoBestia/cargo_reg_local)

**Comment by Mubelotix** [comment] 2020-05-18 11:19
Why is this issue closed? The problem has not been fixed.

**Comment by LucianoBestia** [comment] 2020-05-20 14:15
Sorry for closing. I was just clumsy. I should reopen it.

**Comment by serayuzgur** [comment] 2020-05-21 08:32
I have merged a PR about using local repository index but it is not ready to ship yet. This will be available with v0.5.0

**Comment by serayuzgur** [comment] 2020-05-24 08:33
check  version 0.5.0 please

**Closed by serayuzgur** 2020-05-24 08:33 UTC
Labels: enhancement

**Comment by LucianoBestia** [comment] 2020-05-26 13:40
It works great. Thank you.
The problematic [dependencies.web-sys] now work flawlesly.

![image](https://user-images.githubusercontent.com/31509965/82907568-66f43000-9f84-11ea-94c3-6ee124a92286.png)

**Comment by Mubelotix** [comment] 2020-07-01 08:26
The issue is back. You should reopen @LucianoBestia

**Comment by serayuzgur** [comment] 2020-07-01 08:32
@Mubelotix  please use local repository index

**Comment by Mubelotix** [comment] 2020-07-01 08:35
How is this possible?

**Comment by serayuzgur** [comment] 2020-07-01 08:37
<img width="1250" alt="Screen Shot 2020-07-01 at 11 37 15" src="https://user-images.githubusercontent.com/4561330/86222677-3c9f1f00-bb8f-11ea-9508-221e5a554c81.png">
